language: "en"


# pipeline: tensorflow_embedding
pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_spacy"
  - name: "ner_crf"
  - name: "ner_spacy"
  - name: "ner_synonyms"
  - name: "intent_classifier_tensorflow_embedding"
  # - name: "intent_classifier_sklearn"